name:                OutboxRouter
version:             0.1.0.0
github:              githubuser/OutboxRouter
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/OutboxRouter#readme>

dependencies:
- base >= 4.11 && < 10
- chakra
- rio
- wai
- wai-cli
- http-types
- aeson
- text
- data-has
- envy
- bytestring
- servant-server
- dotenv
- optparse-simple
- resource-pool
- postgresql-simple
- hostname
- async


default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  OutboxRouter-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - OutboxRouter
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T

tests:
  OutboxRouter-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - OutboxRouter
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
